accounts:
  - id: 5be1b31a8a3ef0e1
    alias: Alexandre Viau
    enable: true
    type: RING
    allCodecs: 144/145/146/147/148/149/150/151/152/153/154/
    mailbox: ""
    autoAnswer: false
    activeCallLimit: -1
    ringtoneEnabled: true
    ringtonePath: /usr/share/ring/ringtones/default.wav
    hasCustomUserAgent: false
    useragent: Ring/2.3.0
    username: ring:77c1d3d3d0c4d1427b5e91c95cdc3dccda7d108b
    displayName: Alexandre Viau
    hostname: bootstrap.ring.cx
    upnpEnabled: true
    audioPortMax: 32766
    audioPortMin: 16384
    dtmfType: overrtp
    interface: default
    publishAddr: ""
    publishPort: 5060
    sameasLocal: true
    videoEnabled: true
    videoPortMax: 65534
    videoPortMin: 49152
    stunEnabled: false
    stunServer: ""
    turnEnabled: false
    turnServer: ""
    turnServerUserName: ""
    turnServerPassword: ""
    turnServerRealm: ""
    dhtPort: 7248
    dhtPublicInCalls: true
    allowPeersFromHistory: true
    allowPeersFromContact: true
    allowPeersFromTrusted: true
    tls:
      calist: ""
      certificate: /home/aviau/.local/share/ring/5be1b31a8a3ef0e1/dht.crt
      password: ""
      privateKey: /home/aviau/.local/share/ring/5be1b31a8a3ef0e1/dht.key
preferences:
  historyLimit: 30
  historyMaxCalls: 20
  md5Hash: false
  order: 5be1b31a8a3ef0e1/
  portNum: 5060
  registrationexpire: 180
  searchBarDisplay: true
  zoneToneChoice: North America
voipPreferences:
  playDtmf: true
  playTones: true
  pulseLength: 250
  symmetric: true
  zidFile: zidFile
hooks:
  numberAddPrefix: ""
  sipEnabled: false
  urlCommand: x-www-browser
  urlSipField: X-ring-url
audio:
  alsa:
    cardIn: 0
    cardOut: 0
    cardRing: 0
    plugin: default
    smplRate: 44100
  alwaysRecording: false
  audioApi: pulseaudio
  automaticGainControl: false
  captureMuted: false
  noiseReduce: false
  playbackMuted: false
  pulse:
    devicePlayback: ""
    deviceRecord: ""
    deviceRingtone: ""
  recordPath: ""
  volumeMic: 1
  volumeSpkr: 1
video:
  devices:
    - video_size: 960x540
      channel: Camera 1
      name: Integrated Camera
      framerate: 30
shortcuts:
  hangUp: ""
  pickUp: ""
  popupWindow: ""
  toggleHold: ""
  togglePickupHangup: ""